# Generated by Django 4.1.4 on 2023-01-08 12:24

import django.db.models.deletion
from django.db import (
    migrations,
    models
)


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_board_boardparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcategory',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='goals.board', verbose_name='Доска'),
        ),
    ]
