# Generated by Django 4.1.4 on 2023-01-08 12:27

from django.db import (
    migrations,
    transaction
)
from django.utils import timezone


def forward_func(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Board = apps.get_model('goals', 'Board')
    BoardParticipant = apps.get_model('goals', 'BoardParticipant')
    GoalCategory = apps.get_model('goals', 'GoalCategory')

    with transaction.atomic():  # Применяем все изменения одной транзакцией
        for user in User.objects.all():  # Для каждого пользователя
            new_board = Board.objects.create(
                title='Мои цели',
                created=timezone.now(),
                updated=timezone.now()
            )
            BoardParticipant.objects.create(
                user=user,
                board=new_board,
                role=1,
                created=timezone.now(),
                updated=timezone.now()
            )

            # проставляем всем категориям пользователя его доску
            GoalCategory.objects.filter(user=user).update(board=new_board)


def reverse_func(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Board = apps.get_model('goals', 'Board')
    BoardParticipant = apps.get_model('goals', 'BoardParticipant')
    GoalCategory = apps.get_model('goals', 'GoalCategory')
    with transaction.atomic():
        for user in User.objects.all():  # Для каждого пользователя
            board = Board.objects.filter(
                title='Мои цели',
                board__participants__user=user,
            )
            BoardParticipant.objects.filter(
                user=user,
                board=board,
            ).delete()
            GoalCategory.objects.filter(user=user).update(board=None)
            board.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('goals', '0005_goalcategory_board'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func)
    ]
