# Generated by Django 4.1.4 on 2023-01-12 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='telegram id')),
                ('tg_chat_id', models.BigIntegerField(verbose_name='telegram-чат id')),
                ('username', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='имя пользователя telegram')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='связанный пользователь')),
            ],
            options={
                'verbose_name': 'telegram пользователь',
                'verbose_name_plural': 'telegram пользователи',
            },
        ),
    ]
